<<<<<<< HEAD
spring.application.name=defense-app
=======
# H2 Console + JPA
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

# Affichage des requêtes SQL (correctement commenté)
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true   # décommente si tu veux le SQL formaté
>>>>>>> 41a7bcd87732ce1c6e705e423a622a71d00baed2
